# API Calls
### Environment: localhost
### Get File Path
POST http://localhost:3011/menu/Perfect-plate.yaml
Content-Type: application/json

### Get Menu Items
GET http://localhost:3011/menu/Perfect-plate.yaml
Content-Type: application/json